sudo: false
dist: trusty
language: php
php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
  # Only support the HHVM version that MediaWiki supports.
  # Also, hhvm-3.26 changed its PHP_VERSION from 5.6.99 to 7.1.99 which breaks Composer.
  # – <https://github.com/composer/composer/issues/7361>
  - "hhvm-3.18"
install:
  - composer install
script:
  - composer test
after_success:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar
  - ./coveralls.phar -v
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
